server:
  port: 8888
  
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ytrop/SpringCloudConfig
          default-label: main
          search-paths:
          - '*service'
  
